[project]
name = "react"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "langchain>=0.3.27",
    "langchain-ollama>=0.3.6",
    "openai>=1.97.1",
    "python-dotenv>=1.1.1",
]
